# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-26 07:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighbor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Areacode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(default='e.g Metroplois, Gotham, Starcity etc', max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('occupants_count', models.IntegerField(blank=True, default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('biz_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biz', to='neighbor.Areacode')),
                ('biz_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
