# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-26 13:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighbor', '0004_auto_20200226_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(default='e.g Nairobi, Juja, Kiambu etc', max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('occupants_count', models.IntegerField(blank=True, default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='hoods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='areacode',
            name='user_profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_photo',
            new_name='avatar',
        ),
        migrations.RemoveField(
            model_name='business',
            name='biz_area',
        ),
        migrations.RemoveField(
            model_name='join',
            name='area_id',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_area',
        ),
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Areacode',
        ),
        migrations.AddField(
            model_name='business',
            name='biz_hood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biz', to='neighbor.Neighborhood'),
        ),
        migrations.AddField(
            model_name='join',
            name='hood_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='neighbor.Neighborhood'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_hood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neighbor.Neighborhood'),
        ),
    ]
